version: '3.8'

services:
  front-end:
    build:
      context: ./front-end  # Path to your front-end Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end  # Path to your back-end Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development